configuration: Debug
image: Visual Studio 2019

# hack until donet patching works with PR
init: 
  - cmd: if DEFINED APPVEYOR_PULL_REQUEST_NUMBER (Set build_number=1) ELSE (Set build_number=%APPVEYOR_BUILD_NUMBER%)


environment:
  app_version: '4.0.0'

version: '$(app_version).{build}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  assembly_version: '$(app_version).$(build_number)'
  file_version: '$(app_version).$(build_number)'
  informational_version: '$(app_version).$(build_number)'
  
cache:
  packages -> **\*.csproj  # preserve "packages" directory in the root of build folder but will reset it if a project file is modified

before_build:
 - nuget sources add -name bddhelper -source https://ci.appveyor.com/nuget/ospsuite-bddhelper 
 - nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

test:
  assemblies:
    - OSPSuite.Utility.Tests.dll

skip_commits:
  files:
    - '*.md'

pull_requests: 
  do_not_increment_build_number: true     

nuget: 
  disable_publish_on_pr: true  

skip_branch_with_pr: true

skip_tags: true

branches:
  only:
  - master
  - develop

notifications:
  - provider: Slack
    incoming_webhook:      
      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyFEAs8X080yIO8g1FLt3tNfBN4OpeBnkgrXzf7AqNKV5561x7Coux3ByGrHmsL1sCo=
