configuration: Debug

environment:
  app_version: '2.0.0'
  COVERALLS_REPO_TOKEN:
    secure: 1l5E4XyUlDgQ1WEuuitSh+p1YxjUuUjv0kK0iaYLtsSKELQwLZ/e6txiLoCaDj0t

version: '%app_version%.{build}'

assembly_info:
  patch: true
  file: SolutionInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"	

cache:
  packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

install:
- git submodule update --init --recursive

before_build:
 - nuget sources add -name bddhelper -source https://ci.appveyor.com/nuget/ospsuite-bddhelper 
 - nuget restore

build:
  publish_nuget: true
  verbosity: minimal
  project: OSPSuite.Utility.sln

test_script:
  - rake cover["+[OSPSuite.Utility]*"]

skip_commits:
  files:
    - '*.md'

notifications:
  - provider: Slack
    incoming_webhook:      
      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyF1h7st5qNdNezFp6T+bWXqrcZ4q/smtPcJ7LkUFHL46JDYUFlIL8FDz+ApX/vP+x0=
